services:
  base:
    profiles: [none]
    image: ghcr.io/Kuzma02/Free-Admin-Dashboard
    build: .
    container_name: free-admin-dashboard
    hostname: free-admin-dashboard

  standalone:
    extends: base
    ports:
      - 5173:5173

  dev:
    extends: standalone
    volumes:
      - .:/app
  
